name: "Deploy Azure Functions Package"
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Nome do artefato"
        required: true
        type: string
      environment:
        description: "Ambiente"
        required: true
        type: string
      is-matrix:
        description: "É matrix?"
        required: false
        type: boolean
        default: false
      matrix:
        description: "Matriz"
        required: false
        type: string
        default: ""
    secrets: 
        publish-profile:
            description: "Publish Profile"
            required: false

env:
  ARTIFACT_NAME: ${{ inputs.artifact-name }}

jobs:
  build-artifact:
    if: ${{ inputs.is-matrix }}
    name: "Azure Functions Deploy | ${{ matrix.function-name }}"
    runs-on: ubuntu-latest
    environment: 
        name: ${{ inputs.environment }}
    strategy:
      matrix: ${{ fromJson(inputs.matrix) }}
    steps:
      - name: "Download Artifact of Function App"
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: "Unzip Artifact of Function App"
        shell: bash
        run: |
          unzip ${{env.ARTIFACT_NAME}}.zip -d .
          rm ${{env.ARTIFACT_NAME}}.zip

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: deployFunctionApp
        with:
          app-name: ${{ matrix.function-name }}
          slot-name: ${{ matrix.slot-name }}
          package: "."
          publish-profile: ${{ secrets[matrix.publish-profile] }}